DB_PASSWORD = 'YOUR_DB_PASSWORD'
SECRET_KEY = 'YOUR_DJANGO_SECRET_KEY_ANY_RANDOM_TEXT_WILL_DO'

TWITTER_CONSUMER_KEY = 'GET_THIS_FROM_TWITTER'
TWITTER_CONSUMER_SECRET = 'GET_THIS_FROM_TWITTER'
TWITTER_ACCESS_TOKEN_KEY = 'GET_THIS_FROM_TWITTER'
TWITTER_ACCESS_TOKEN_SECRET = 'GET_THIS_FROM_TWITTER'
