# Generated by Django 2.0.6 on 2018-06-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('event_id', models.CharField(max_length=66, primary_key=True, serialize=False)),
                ('twitter_id', models.CharField(max_length=32, null=True, unique=True)),
                ('tweeted_ts', models.DateTimeField()),
                ('question_id', models.CharField(editable=False, max_length=66)),
                ('block_id', models.IntegerField()),
            ],
        ),
    ]
