// Browser IIFE entry: exposes parsing/formatting helpers as window.RealityLib
export {
    delimiter,
    populatedJSONForTemplate,
    parseQuestionJSON,
    encodeText,
    encodeCustomText,
    answerHash,
    answerToBytes32,
    bytes32ToString,
    getAnswerString,
    contentHash,
    questionID,
    hasInvalidOption,
    hasAnsweredTooSoonOption,
    getInvalidValue,
    getAnsweredTooSoonValue,
    minNumber,
    maxNumber,
    arrayToBitmaskBigNumber,
    padToBytes32,
    convertTsToString,
    secondsTodHms,
    guessTemplateConfig,
    getLanguage,
    commitmentID,
    shortDisplayQuestionID,
} from './src/formatters/question.js';

export {
    preloadedTemplateContents,
    preloadedTemplateContentsV32,
    defaultTemplateIDForType,
    defaultTemplateForType,
} from './src/formatters/template.js';
