import { createConfig } from "@ponder/core";
import { http, type Transport } from "viem";
import { readFileSync } from "fs";
import { join } from "path";

// v3.2 ABI is a superset of all earlier versions; events are identical across
// v2.0, v2.1, v3.0, v3.2, and the ERC20 variants, so one ABI covers everything.
import abi from "../contracts/abi/solc-0.8.6/RealityETH-3.2.abi.json";

// Known event blocks per chain, generated by scripts/fetch-event-blocks.js.
// When present for a chain, eth_getLogs for a range with no known event block
// is short-circuited with [] immediately; ranges that DO contain event blocks
// are resolved via individual per-block calls rather than wide range queries.
// Re-run the script when contracts or start blocks change.
function loadKnownEventBlocks(): Record<string, number[]> {
  try {
    const raw = JSON.parse(readFileSync(join(__dirname, 'known-event-blocks.json'), 'utf8'));
    for (const chain of Object.keys(raw)) {
      raw[chain] = (raw[chain] as number[]).sort((a, b) => a - b);
      console.log(`[sparse] ${chain}: ${raw[chain].length} known event blocks loaded`);
    }
    return raw;
  } catch {
    return {};
  }
}
const KNOWN_EVENT_BLOCKS = loadKnownEventBlocks();

// High-water mark per chain: the highest block number covered by the sparse cache.
// eth_getLogs for blocks BEYOND this are realtime (new events not yet in cache)
// and must be forwarded to the RPC rather than sparse-skipped.
function loadKnownBlockHwm(): Record<string, number> {
  try {
    const raw = JSON.parse(readFileSync(join(__dirname, 'known-event-blocks-meta.json'), 'utf8'));
    const result: Record<string, number> = {};
    for (const [chain, contracts] of Object.entries(raw as Record<string, Record<string, number>>)) {
      const hwms = Object.values(contracts);
      if (hwms.length > 0) result[chain] = Math.min(...hwms);
    }
    return result;
  } catch {
    return {};
  }
}
const KNOWN_BLOCK_HWM = loadKnownBlockHwm();

// Returns all known-event block numbers in [from, to] from a sorted array.
function knownBlocksInRange(blocks: number[], from: number, to: number): number[] {
  let lo = 0, hi = blocks.length;
  while (lo < hi) { const mid = (lo + hi) >> 1; if (blocks[mid] < from) lo = mid + 1; else hi = mid; }
  const result: number[] = [];
  while (lo < blocks.length && blocks[lo] <= to) result.push(blocks[lo++]);
  return result;
}

// Backoff delays (ms) for eth_getLogs / eth_getBlockByNumber failures.
// After the last value is reached it repeats; after ALERT_STREAK consecutive
// max-delay failures a log alert is emitted (and a recovery log on success).
const BACKOFF_MS = [3, 6, 12, 24, 48, 96, 192].map(s => s * 1000);
const ALERT_STREAK = 10;

function describeArgs(args: any): string {
  if (args.method === 'eth_getLogs') {
    const [filter] = args.params ?? [];
    if (filter?.fromBlock && filter?.toBlock) {
      const from  = parseInt(filter.fromBlock, 16);
      const to    = parseInt(filter.toBlock,   16);
      return ` [logs ${from}–${to}, range ${to - from}]`;
    }
  } else if (args.method === 'eth_getBlockByNumber') {
    const [blockHex] = args.params ?? [];
    if (blockHex) return ` [block ${parseInt(blockHex, 16)}]`;
  }
  return '';
}

// Wraps a transport so that eth_getLogs and eth_getBlockByNumber failures back
// off and retry rather than crashing the whole Ponder process. Other RPC methods
// pass through unchanged. Per-chain state lives in a closure.
// lastUrl is a shared ref updated by routed() before each request so logs show
// which endpoint was actually used.
function resilient(chain: string, inner: Transport, lastUrl: { value: string }): Transport {
  let errors   = 0;
  let maxCount = 0;
  let notified = false;

  return ((params: any) => {
    const t = (inner as any)(params);
    return {
      ...t,
      request: async (args: any) => {
        if (args.method !== 'eth_getLogs' && args.method !== 'eth_getBlockByNumber') {
          return t.request(args);
        }
        for (;;) {
          try {
            const result = await t.request(args);
            if (errors > 0) {
              const msg = `[${chain}] RPC recovered after ${errors} consecutive failures @ ${lastUrl.value}${describeArgs(args)}`;
              if (notified) {
                console.error(`[RECOVERY] ${msg}`);
              } else {
                console.warn(msg);
              }
              errors = 0; maxCount = 0; notified = false;
            }
            return result;
          } catch (err: any) {
            if (err?._isRangeCap) throw err;
            const atMax = errors >= BACKOFF_MS.length - 1;
            const delayMs = BACKOFF_MS[Math.min(errors, BACKOFF_MS.length - 1)];
            errors++;
            if (atMax) {
              maxCount++;
              if (maxCount === ALERT_STREAK && !notified) {
                console.error(`[ALERT] [${chain}] ${args.method} has been failing for ${errors} consecutive attempts with no recovery — manual intervention may be required`);
                notified = true;
              }
            }
            const endpoint = err?.url ?? lastUrl.value;
            const status   = err?.status ? ` HTTP ${err.status}` : '';
            const detail   = err?.shortMessage ?? err?.message ?? String(err);
            console.warn(`[${chain}] ${args.method} failed (attempt ${errors}, retry in ${delayMs / 1000}s) @ ${endpoint}${status}${describeArgs(args)}: ${detail}`);
            await new Promise(r => setTimeout(r, delayMs));
          }
        }
      },
    };
  }) as unknown as Transport;
}

// Routes eth_getLogs to wideUrl when the block range exceeds WIDE_THRESHOLD,
// and to narrowUrl otherwise. This lets a wide-range provider (e.g. Infura)
// handle historical sync while a narrow provider (e.g. Alchemy free tier)
// handles polling, which only ever queries a handful of new blocks at a time.
// lastUrl is updated before each request so resilient() can log which endpoint was used.
const WIDE_THRESHOLD  = 9;    // Alchemy free tier rejects eth_getLogs with more than 10 blocks (to-from > 9)
const MAX_WIDE_RANGE  = 2000; // Infura free tier limit; also caps runaway adaptive range growth on sparse chains

function hostOf(u: string): string {
  const m = u.match(/^https?:\/\/([^/]+)/);
  return m ? m[1] : u;
}

// Per-chain approximate genesis Unix timestamps and average block times (seconds).
// Used to estimate timestamps for synthetic blocks so that ponder's checkpoint
// comparisons (which use blockTimestamp as the primary sort key) remain correct.
// Values are calibrated from actual genesis times and current block/time ratios;
// precision within a few percent is sufficient — we only need correct ordering.
const CHAIN_GENESIS: Record<string, { genesis: number; blockTime: number }> = {
  mainnet:  { genesis: 1438269988, blockTime: 13.55 }, // Jul 2015; avg of 15s pre-Merge + 12s post-Merge
  gnosis:   { genesis: 1539024827, blockTime: 5.0   }, // Oct 2018 (xDai)
  polygon:  { genesis: 1590824836, blockTime: 2.2   }, // May 2020
  arbitrum: { genesis: 1622419200, blockTime: 0.335 }, // May 2021; avg over variable early/late periods
  optimism: { genesis: 1610643600, blockTime: 2.0   }, // Jan 2021
  sepolia:  { genesis: 1633267200, blockTime: 12.0  }, // Oct 2021 (testnet)
  unichain: { genesis: 1709000000, blockTime: 1.0   }, // Feb 2024 (approx)
  base:     { genesis: 1689200000, blockTime: 2.0   }, // Jul 2023
};

// Minimal synthetic block returned for blocks outside our known-event-blocks list.
// Ponder calls eth_getBlockByNumber for every range endpoint during historical sync
// even when getLogs returns [] — returning a fake block immediately avoids the RPC
// round-trip and lets ponder's estimateRange grow quickly to MAX_WIDE_RANGE.
// Real data is only needed for blocks that actually contain events.
//
// IMPORTANT: timestamp must be a reasonable estimate, NOT 0x0. Ponder encodes
// blockTimestamp as the primary sort key in its checkpoint strings and uses them
// to decide which events to yield from getEvents(). A zero timestamp would put
// every synthetic checkpoint before all real event checkpoints, causing getEvents()
// to return nothing and leaving all user tables permanently empty.
function syntheticBlock(chain: string, blockNum: number): object {
  const hex  = (n: number) => `0x${n.toString(16)}`;
  const pad  = (n: number) => `0x${n.toString(16).padStart(64, '0')}`;
  const zero = '0x' + '00'.repeat(32);
  const { genesis, blockTime } = CHAIN_GENESIS[chain] ?? { genesis: 1000000000, blockTime: 12 };
  const estimatedTs = Math.floor(genesis + blockNum * blockTime);
  return {
    hash:             pad(blockNum),
    parentHash:       pad(blockNum > 0 ? blockNum - 1 : 0),
    number:           hex(blockNum),
    timestamp:        hex(estimatedTs),
    nonce:            null,
    difficulty:       '0x0',
    totalDifficulty:  null,
    gasLimit:         '0x1c9c380',
    gasUsed:          '0x0',
    size:             '0x1',
    miner:            '0x0000000000000000000000000000000000000000',
    extraData:        '0x',
    logsBloom:        '0x' + '00'.repeat(256),
    mixHash:          zero,
    sha3Uncles:       '0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347',
    stateRoot:        zero,
    transactionsRoot: '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
    receiptsRoot:     '0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421',
    baseFeePerGas:    null,
    withdrawalsRoot:  null,
    transactions:     [],
    withdrawals:      [],
  };
}

function routed(chain: string, narrowUrl: string, wideUrl: string | undefined, narrowOpts: object, wideOpts: object, lastUrl: { value: string }): Transport {
  const sparseBlocks    = KNOWN_EVENT_BLOCKS[chain] ?? null;
  const sparseHwm       = KNOWN_BLOCK_HWM[chain] ?? 0;
  const knownBlocksSet  = sparseBlocks ? new Set<number>(sparseBlocks) : null;
  const narrowHttp      = http(narrowUrl, narrowOpts);
  const wideHttp        = wideUrl ? http(wideUrl, wideOpts) : narrowHttp;
  const narrowHost      = hostOf(narrowUrl);
  const wideHost        = wideUrl ? hostOf(wideUrl) : narrowHost;
  let   sparseSkipped   = 0;
  let   syntheticServed = 0;
  return ((params: any) => {
    const n = (narrowHttp as any)(params);
    const w = (wideHttp  as any)(params);
    return {
      ...n,
      request: async (args: any) => {
        if (args.method === 'eth_getLogs') {
          const [filter] = args.params ?? [];
          if (filter?.fromBlock && filter?.toBlock) {
            const from = parseInt(filter.fromBlock, 16);
            const to   = parseInt(filter.toBlock,   16);

            if (sparseBlocks && to <= sparseHwm) {
              // Historical range fully within our sparse cache.
              // Either skip (no events) or make one targeted getLogs per event block.
              const targets = knownBlocksInRange(sparseBlocks, from, to);
              if (targets.length === 0) {
                const n2 = ++sparseSkipped;
                if (n2 <= 5 || n2 % 500 === 0)
                  process.stderr.write(`[${chain}] eth_getLogs [${from}–${to}, range ${to - from}] → sparse #${n2}\n`);
                return [];
              }
              process.stderr.write(`[${chain}] eth_getLogs [${from}–${to}] → ${targets.length} targeted on ${narrowHost}\n`);
              lastUrl.value = narrowUrl;
              const allLogs: any[] = [];
              for (const blockNum of targets) {
                const blockHex = `0x${blockNum.toString(16)}`;
                const logs = await n.request({
                  ...args,
                  params: [{ ...filter, fromBlock: blockHex, toBlock: blockHex }],
                }) as any[];
                process.stderr.write(`[${chain}] eth_getLogs block ${blockNum} ← ${logs.length} log(s)\n`);
                allLogs.push(...logs);
              }
              return allLogs;
            }

            // Realtime / spanning / non-sparse: route to wide/narrow RPC.
            // (Targeted optimization only applies for to <= sparseHwm above.)
            if ((to - from) > MAX_WIDE_RANGE) {
              process.stderr.write(`[${chain}] eth_getLogs [${from}–${to}, range ${to - from}] → rechunk\n`);
              throw {
                message:      `eth_getLogs limited to a ${MAX_WIDE_RANGE} blocks`,
                shortMessage: `eth_getLogs limited to a ${MAX_WIDE_RANGE} blocks`,
                code: -32602,
                _isRangeCap: true,
              };
            }
            const tag = (sparseBlocks && from > sparseHwm) ? 'realtime' : (sparseBlocks && to > sparseHwm) ? 'span' : '';
            if (wideUrl && (to - from) > WIDE_THRESHOLD) {
              lastUrl.value = wideUrl;
              process.stderr.write(`[${chain}] eth_getLogs [${from}–${to}, range ${to - from}]${tag ? ` (${tag})` : ''} → wide (${wideHost})\n`);
              return w.request(args);
            }
            process.stderr.write(`[${chain}] eth_getLogs [${from}–${to}, range ${to - from}]${tag ? ` (${tag})` : ''} → narrow (${narrowHost})\n`);
          }
        } else if (args.method === 'eth_getBlockByNumber') {
          const [blockHex] = args.params ?? [];
          const req = blockHex === 'latest' ? 'latest' : parseInt(blockHex, 16);
          // Return a synthetic block instantly for specific blocks that aren't
          // known event blocks — ponder only needs these to advance the sync
          // cursor; getLogs for those ranges returns [] so nothing references them.
          // Only return a synthetic block when the requested block is (a) strictly
          // below the sparseHwm and (b) not a known-event block. Beyond the HWM,
          // real blocks may have real events; ponder would cross-check log.blockHash
          // against block.hash and get a fatal "inconsistent RPC responses" error if
          // it receives the synthetic fake hash.
          if (typeof req === 'number' && knownBlocksSet && !knownBlocksSet.has(req) && req < sparseHwm) {
            const n2 = ++syntheticServed;
            if (n2 <= 5 || n2 % 500 === 0)
              process.stderr.write(`[${chain}] eth_getBlockByNumber ${req} → synthetic #${n2}\n`);
            return syntheticBlock(chain, req);
          }
          process.stderr.write(`[${chain}] eth_getBlockByNumber ${req} → ${narrowHost}\n`);
          lastUrl.value = narrowUrl;
          const result = await n.request(args);
          const num = result?.number != null ? parseInt(result.number, 16) : '?';
          process.stderr.write(`[${chain}] eth_getBlockByNumber ${req} ← ${num}\n`);
          return result;
        } else {
          process.stderr.write(`[${chain}] RPC ${args.method} → ${narrowHost}\n`);
        }
        lastUrl.value = narrowUrl;
        return n.request(args);
      },
    };
  }) as unknown as Transport;
}

// Build a network config. Chain is only included if its RPC URL env var is set.
// Wide requests get a longer timeout and no viem-level retries — our resilient()
// wrapper handles retries so viem's silent internal retries don't mask failures.
function net(chain: string, chainId: number, narrowUrl: string, wideUrl?: string, maxRequestsPerSecond = 5, pollingInterval = 1_000) {
  const narrowOpts = { timeout: 30_000, retryCount: 2, retryDelay: 2000 };
  const wideOpts   = { timeout: 90_000, retryCount: 1 };
  const lastUrl    = { value: narrowUrl };
  return {
    chainId,
    maxRequestsPerSecond,
    pollingInterval,
    transport: resilient(chain, routed(chain, narrowUrl, wideUrl, narrowOpts, wideOpts, lastUrl), lastUrl),
  };
}

// A chain is included only if its RPC URL is set AND it isn't in PONDER_DISABLE.
// Example: PONDER_DISABLE=mainnet,sepolia
const DISABLED = new Set(
  (process.env.PONDER_DISABLE || '').split(',').map(s => s.trim()).filter(Boolean)
);
const url  = (name: string, envVar: string): string =>
  !DISABLED.has(name) ? (process.env[envVar] ?? '') : '';
const wide = (name: string, envVar: string): string | undefined =>
  !DISABLED.has(name) ? (process.env[envVar] || undefined) : undefined;

export default createConfig({
  networks: {
    ...(url('gnosis',   'PONDER_RPC_URL_100')      && { gnosis:   net('gnosis',   100,      url('gnosis',   'PONDER_RPC_URL_100'),      wide('gnosis',   'PONDER_RPC_URL_100_WIDE'),   5, 5_000) }),
    ...(url('mainnet',  'PONDER_RPC_URL_1')        && { mainnet:  net('mainnet',  1,        url('mainnet',  'PONDER_RPC_URL_1'),        wide('mainnet',  'PONDER_RPC_URL_1_WIDE'),   5, 12_000) }),
    ...(url('arbitrum', 'PONDER_RPC_URL_42161')    && { arbitrum: net('arbitrum', 42161,    url('arbitrum', 'PONDER_RPC_URL_42161'),    wide('arbitrum', 'PONDER_RPC_URL_42161_WIDE'), 5, 300_000) }),
    ...(url('sepolia',  'PONDER_RPC_URL_11155111') && { sepolia:  net('sepolia',  11155111, url('sepolia',  'PONDER_RPC_URL_11155111'), wide('sepolia',  'PONDER_RPC_URL_11155111_WIDE'), 5, 30_000) }),
    ...(url('polygon',  'PONDER_RPC_URL_137')      && { polygon:  net('polygon',  137,      url('polygon',  'PONDER_RPC_URL_137'),      wide('polygon',  'PONDER_RPC_URL_137_WIDE'),      Number(process.env.PONDER_RPC_MAX_RPS_137 || 5), 15_000) }),
    ...(url('unichain', 'PONDER_RPC_URL_130')      && { unichain: net('unichain', 130,      url('unichain', 'PONDER_RPC_URL_130'),      wide('unichain', 'PONDER_RPC_URL_130_WIDE'),      5, 8_000) }),
    ...(url('optimism', 'PONDER_RPC_URL_10')  && { optimism: net('optimism', 10,   url('optimism', 'PONDER_RPC_URL_10'),  wide('optimism', 'PONDER_RPC_URL_10_WIDE'),  Number(process.env.PONDER_RPC_MAX_RPS_10   || 5), 30_000) }),
    ...(url('base',     'PONDER_RPC_URL_8453') && { base:    net('base',    8453,  url('base',     'PONDER_RPC_URL_8453'), wide('base',     'PONDER_RPC_URL_8453_WIDE'), 5,                                              30_000) }),
  },

  contracts: {
    // v3.2 — most recent deployment.
    RealityETH_v3_2: {
      abi,
      network: {
        ...(url('mainnet', 'PONDER_RPC_URL_1') && { mainnet: { address: "0x6a2155613b68eFB38D5c6074921F3F4281c8c177", startBlock: 22100226 } }),
        ...(url('gnosis', 'PONDER_RPC_URL_100')  && { gnosis:  { address: "0xEb51d9d9717906c981C57af09C4a3449eF30705b", startBlock: 39142627 } }),
        ...(url('sepolia', 'PONDER_RPC_URL_11155111') && { sepolia: { address: "0xB7982f20CC159a40eba4b0eA86fd6cbA6Ff810e1", startBlock: 7898415  } }),
      },
    },

    // v3.0 — active since 2021 across all chains.
    RealityETH_v3_0: {
      abi,
      network: {
        ...(url('mainnet', 'PONDER_RPC_URL_1')  && { mainnet:  { address: "0x5b7dD1E86623548AF054A4985F7fc8Ccbb554E2c", startBlock: 13194676 } }),
        ...(url('gnosis', 'PONDER_RPC_URL_100')   && { gnosis:   { address: "0xE78996A233895bE74a66F451f1019cA9734205cc", startBlock: 17997262 } }),
        ...(url('arbitrum', 'PONDER_RPC_URL_42161')    && { arbitrum: { address: "0x5D18bD4dC5f1AC8e9bD9B666Bd71cB35A327C4A9", startBlock: 459975   } }),
        ...(url('sepolia',  'PONDER_RPC_URL_11155111') && { sepolia:  { address: "0xaf33DcB6E8c5c4D9dDF579f53031b514d19449CA", startBlock: 3044431  } }),
        ...(url('polygon',  'PONDER_RPC_URL_137')      && { polygon:  { address: "0x60573B8DcE539aE5bF9aD7932310668997ef0428", startBlock: 18901674 } }),
        ...(url('unichain', 'PONDER_RPC_URL_130')  && { unichain: { address: "0xB920dBedE88B42aA77eE55ebcE3671132ee856fC", startBlock: 8561869  } }),
        ...(url('optimism', 'PONDER_RPC_URL_10')   && { optimism: { address: "0x0eF940F7f053a2eF5D6578841072488aF0c7d89A", startBlock: 2462149  } }),
        ...(url('base',     'PONDER_RPC_URL_8453')  && { base:     { address: "0x2F39f464d16402Ca3D8527dA89617b73DE2F60e8", startBlock: 26260675 } }),
        // celo:      { address: "0x4C2863bb9969dD693Ec487bED72BDfD83C0cA5b3", startBlock: 31954377 },
        // avalanche: { address: "0xD88cd78631Ea0D068cedB0d1357a6eabe59D7502", startBlock: 4090592  },
      },
    },

    // v2.1 — Gnosis and Arbitrum, predates v3.0.
    ...((url('gnosis', 'PONDER_RPC_URL_100') || url('arbitrum', 'PONDER_RPC_URL_42161') || url('polygon', 'PONDER_RPC_URL_137')) && { RealityETH_v2_1: {
      abi,
      network: {
        ...(url('gnosis',   'PONDER_RPC_URL_100')   && { gnosis:   { address: "0x79e32aE03fb27B07C89c0c568F80287C01ca2E57", startBlock: 14005802 } }),
        ...(url('arbitrum', 'PONDER_RPC_URL_42161') && { arbitrum: { address: "0x0EDB4CB0B12523749c56Ff24C4a09c0c1417f691", startBlock: 112029   } }),
        ...(url('polygon',  'PONDER_RPC_URL_137')   && { polygon:  { address: "0xA75AE6D61Dd9d55e8153A393E2fc859c6a0FC716", startBlock: 15610082 } }),
      },
    }}),

    // v2.0 — Snapshot used this heavily on mainnet. Long history from block ~6.5M (2019).
    ...(url('mainnet', 'PONDER_RPC_URL_1') && { RealityETH_v2_0: {
      abi,
      network: {
        mainnet: { address: "0x325a2e0F3CCA2ddbaeBB4DfC38Df8D19ca165b47", startBlock: 6531265 },
      },
    }}),

    // ERC20 token-denominated variants — same events, grouped per chain.
    // Mainnet: TRST/GNO/FOX (v2.0), GNO/SWISE (v3.0)
    ...(url('mainnet', 'PONDER_RPC_URL_1') && { RealityETH_ERC20_mainnet: {
      abi,
      network: {
        mainnet: {
          address: [
            "0x3D3B51b1091d1F6491AeB1916C94BAfe57f6Cc9d", // TRST v2.0, block 8050824
            "0x8f1CC53bf34932591177CDA24723486205CA7510", // GNO v2.0, block 12654677
            "0xf4585A9944A390615E7cec6756C1c082173B93eB", // FOX v2.0, block 12821080
            "0x33aa365a53a4c9ba777fb5f450901a8eef73f0a9", // GNO v3.0, block 13201169
            "0x867092A32bC16816F12Fb326EfF7A2865E1ec138", // SWISE v3.0, block 14485577
          ],
          startBlock: 8050824,
        },
      },
    }}),

    // Gnosis: GNO/SWISE/POLK (v3.0)
    ...(url('gnosis', 'PONDER_RPC_URL_100') && { RealityETH_ERC20_gnosis: {
      abi,
      network: {
        gnosis: {
          address: [
            "0x95b2b2b4b66A5a47Df79bF07BEBe72E9870fceb2", // GNO v3.0, block 20882108
            "0xC9FbdF0df8dE06Ad8d2193F7FA28bdA78c13a102", // SWISE v3.0, block 21371853
            "0x934326a86A99DaB25bB8329089ce73ed9c7c0E4a", // POLK v3.0, block 34578493
          ],
          startBlock: 20882108,
        },
      },
    }}),

    // Polygon: POLK token (v3.0 ERC20)
    ...(url('polygon', 'PONDER_RPC_URL_137') && { RealityETH_ERC20_polygon: {
      abi,
      network: {
        polygon: {
          address: "0x83d3f4769a19f1b43337888b0290f5473cf508b2", // POLK v3.0, block 42899867
          startBlock: 42899867,
        },
      },
    }}),

    // Sepolia: BOND token (v3.2 ERC20)
    ...(url('sepolia', 'PONDER_RPC_URL_11155111') && { RealityETH_ERC20_sepolia: {
      abi,
      network: {
        sepolia: {
          address: "0x8A5f1C6361E280348a59daC10160A88428FFBd51", // BOND v3.2, block 8526475
          startBlock: 8526475,
        },
      },
    }}),

  },
});
