// AUTO-GENERATED by packages/contracts/scripts/generate_ponder_config.js
// Do not edit by hand — run `cd packages/contracts && npm run generate-ponder-config`
import { createConfig } from "ponder";
import type { Abi } from "abitype";
import rawAbi from "@reality.eth/contracts/abi/solc-0.8.6/RealityETH-3.2.abi.json";
const abi = rawAbi as unknown as Abi;

const has = (id: number) => !!process.env[`PONDER_RPC_URL_${id}`];
const rpc = (id: number) => process.env[`PONDER_RPC_URL_${id}`] as string;
const rps = (id: number) => process.env[`PONDER_RPC_MAX_RPS_${id}`] ? { maxRequestsPerSecond: Number(process.env[`PONDER_RPC_MAX_RPS_${id}`]) } : {};

export default createConfig({
  chains: {
    ...(has(1) && { mainnet: { id: 1, rpc: rpc(1), pollingInterval: 12_000, ...rps(1) } }),
    ...(has(100) && { gnosis: { id: 100, rpc: rpc(100), pollingInterval: 5_000, ...rps(100) } }),
    ...(has(10) && { optimism: { id: 10, rpc: rpc(10), pollingInterval: 30_000, ...rps(10) } }),
    ...(has(8453) && { base: { id: 8453, rpc: rpc(8453), pollingInterval: 30_000, ...rps(8453) } }),
    ...(has(42161) && { arbitrum_one: { id: 42161, rpc: rpc(42161), pollingInterval: 300_000, ...rps(42161) } }),
    ...(has(56) && { bsc: { id: 56, rpc: rpc(56), pollingInterval: 3_000, ...rps(56) } }),
    ...(has(130) && { unichain: { id: 130, rpc: rpc(130), pollingInterval: 8_000, ...rps(130) } }),
    ...(has(137) && { matic: { id: 137, rpc: rpc(137), pollingInterval: 15_000, ...rps(137) } }),
    ...(has(11155111) && { sepolia: { id: 11155111, rpc: rpc(11155111), pollingInterval: 30_000, ...rps(11155111) } }),
    ...(has(4) && { rinkeby: { id: 4, rpc: rpc(4), pollingInterval: 15_000, ...rps(4) } }),
    ...(has(5) && { goerli: { id: 5, rpc: rpc(5), pollingInterval: 15_000, ...rps(5) } }),
    ...(has(8) && { ubiq: { id: 8, rpc: rpc(8), pollingInterval: 30_000, ...rps(8) } }),
    ...(has(30) && { rootstock: { id: 30, rpc: rpc(30), pollingInterval: 15_000, ...rps(30) } }),
    ...(has(31) && { rootstock_testnet: { id: 31, rpc: rpc(31), pollingInterval: 15_000, ...rps(31) } }),
    ...(has(40) && { telosevm: { id: 40, rpc: rpc(40), pollingInterval: 30_000, ...rps(40) } }),
    ...(has(69) && { kovan: { id: 69, rpc: rpc(69), pollingInterval: 15_000, ...rps(69) } }),
    ...(has(77) && { poa_sokol: { id: 77, rpc: rpc(77), pollingInterval: 15_000, ...rps(77) } }),
    ...(has(97) && { chapel: { id: 97, rpc: rpc(97), pollingInterval: 3_000, ...rps(97) } }),
    ...(has(143) && { monad: { id: 143, rpc: rpc(143), pollingInterval: 10_000, ...rps(143) } }),
    ...(has(280) && { zksync2_testnet: { id: 280, rpc: rpc(280), pollingInterval: 15_000, ...rps(280) } }),
    ...(has(300) && { zksync_sepolia: { id: 300, rpc: rpc(300), pollingInterval: 30_000, ...rps(300) } }),
    ...(has(324) && { zksync_era: { id: 324, rpc: rpc(324), pollingInterval: 30_000, ...rps(324) } }),
    ...(has(690) && { redstone: { id: 690, rpc: rpc(690), pollingInterval: 30_000, ...rps(690) } }),
    ...(has(777) && { cheapeth: { id: 777, rpc: rpc(777), pollingInterval: 15_000, ...rps(777) } }),
    ...(has(1101) && { polygon_zkevm: { id: 1101, rpc: rpc(1101), pollingInterval: 30_000, ...rps(1101) } }),
    ...(has(1301) && { unichain_sepolia: { id: 1301, rpc: rpc(1301), pollingInterval: 10_000, ...rps(1301) } }),
    ...(has(10200) && { chiado: { id: 10200, rpc: rpc(10200), pollingInterval: 15_000, ...rps(10200) } }),
    ...(has(17000) && { holesky: { id: 17000, rpc: rpc(17000), pollingInterval: 30_000, ...rps(17000) } }),
    ...(has(42220) && { celo: { id: 42220, rpc: rpc(42220), pollingInterval: 30_000, ...rps(42220) } }),
    ...(has(43114) && { avalanche: { id: 43114, rpc: rpc(43114), pollingInterval: 30_000, ...rps(43114) } }),
    ...(has(80001) && { mumbai: { id: 80001, rpc: rpc(80001), pollingInterval: 15_000, ...rps(80001) } }),
    ...(has(84532) && { base_sepolia: { id: 84532, rpc: rpc(84532), pollingInterval: 30_000, ...rps(84532) } }),
    ...(has(421611) && { arbitrum_rinkeby: { id: 421611, rpc: rpc(421611), pollingInterval: 15_000, ...rps(421611) } }),
    ...(has(421613) && { arbitrum_goerli: { id: 421613, rpc: rpc(421613), pollingInterval: 30_000, ...rps(421613) } }),
    ...(has(421614) && { arbitrum_sepolia: { id: 421614, rpc: rpc(421614), pollingInterval: 30_000, ...rps(421614) } }),
    ...(has(534353) && { scroll_alpha: { id: 534353, rpc: rpc(534353), pollingInterval: 15_000, ...rps(534353) } }),
    ...(has(1337702) && { kintsugi: { id: 1337702, rpc: rpc(1337702), pollingInterval: 15_000, ...rps(1337702) } }),
    ...(has(11155420) && { optimism_sepolia: { id: 11155420, rpc: rpc(11155420), pollingInterval: 30_000, ...rps(11155420) } }),
    ...(has(88558801) && { backstoptestnet1: { id: 88558801, rpc: rpc(88558801), pollingInterval: 10_000, ...rps(88558801) } }),
  },
  contracts: {
    ...((has(1) || has(100) || has(11155111) || has(30) || has(31) || has(143) || has(10200) || has(88558801)) && { RealityETH_v3_2: {
      abi,
      chain: {
        ...(has(1) && { mainnet: { address: "0x6a2155613b68eFB38D5c6074921F3F4281c8c177", startBlock: 22100226 } }),
        ...(has(100) && { gnosis: { address: "0xEb51d9d9717906c981C57af09C4a3449eF30705b", startBlock: 39142627 } }),
        ...(has(11155111) && { sepolia: { address: "0xB7982f20CC159a40eba4b0eA86fd6cbA6Ff810e1", startBlock: 7898415 } }),
        ...(has(30) && { rootstock: { address: "0x4396DB62818eFd4dbcf34A069047E66dB4a1cc66", startBlock: 9206460 } }),
        ...(has(31) && { rootstock_testnet: { address: "0xD9C19E152948FF34A817c75D022af9b7Ac8BD5bA", startBlock: 8039801 } }),
        ...(has(143) && { monad: { address: "0xa317A7B24d72e3C6cD55c8F244AE01398A8D97e1", startBlock: 48537242 } }),
        ...(has(10200) && { chiado: { address: "0x012fb3aDce7D60672cF634e730927Fa5822b3cAb", startBlock: 14880291 } }),
        ...(has(88558801) && { backstoptestnet1: { address: "0x3a9Ef99956021d545214B7021D449ACb20fCF2b3", startBlock: 240 } }),
      },
    }}),

    ...((has(1) || has(100) || has(10) || has(8453) || has(42161) || has(56) || has(130) || has(137) || has(11155111) || has(4) || has(5) || has(8) || has(40) || has(69) || has(77) || has(97) || has(280) || has(300) || has(324) || has(690) || has(777) || has(1101) || has(1301) || has(10200) || has(17000) || has(42220) || has(43114) || has(80001) || has(84532) || has(421611) || has(421613) || has(421614) || has(534353) || has(1337702) || has(11155420) || has(88558801)) && { RealityETH_v3_0: {
      abi,
      chain: {
        ...(has(1) && { mainnet: { address: "0x5b7dD1E86623548AF054A4985F7fc8Ccbb554E2c", startBlock: 13194676 } }),
        ...(has(100) && { gnosis: { address: "0xE78996A233895bE74a66F451f1019cA9734205cc", startBlock: 17997262 } }),
        ...(has(10) && { optimism: { address: "0x0eF940F7f053a2eF5D6578841072488aF0c7d89A", startBlock: 2462149 } }),
        ...(has(8453) && { base: { address: "0x2F39f464d16402Ca3D8527dA89617b73DE2F60e8", startBlock: 26260675 } }),
        ...(has(42161) && { arbitrum_one: { address: "0x5D18bD4dC5f1AC8e9bD9B666Bd71cB35A327C4A9", startBlock: 459975 } }),
        ...(has(56) && { bsc: { address: "0xa925646Cae3721731F9a8C886E5D1A7B123151B9", startBlock: 10751380 } }),
        ...(has(130) && { unichain: { address: "0xB920dBedE88B42aA77eE55ebcE3671132ee856fC", startBlock: 8561869 } }),
        ...(has(137) && { matic: { address: "0x60573B8DcE539aE5bF9aD7932310668997ef0428", startBlock: 18901674 } }),
        ...(has(11155111) && { sepolia: { address: "0xaf33DcB6E8c5c4D9dDF579f53031b514d19449CA", startBlock: 3044431 } }),
        ...(has(4) && { rinkeby: { address: "0xDf33060F476F8cff7511F806C72719394da1Ad64", startBlock: 9106451 } }),
        ...(has(5) && { goerli: { address: "0x6F80C5cBCF9FbC2dA2F0675E56A5900BB70Df72f", startBlock: 7313546 } }),
        ...(has(8) && { ubiq: { address: "0x23C7eE4F42e473AEf51C3f59D7D58E33a63Ab348", startBlock: 1670257 } }),
        ...(has(40) && { telosevm: { address: "0xfd6f6A4181B7df7cd539Ac5ea7b6533869AE9BF1", startBlock: 299104399 } }),
        ...(has(69) && { kovan: { address: "0x327543eaf65FE0D68333d4D092282cDBA0Bc37a6", startBlock: 28282 } }),
        ...(has(77) && { poa_sokol: { address: "0xC3324405793B9F1C29e97b29cB084C9541aD4d9B", startBlock: 22647153 } }),
        ...(has(97) && { chapel: { address: "0x16E0a06b00020764F3f50bd2E03D73Da0253A6eA", startBlock: 25029439 } }),
        ...(has(280) && { zksync2_testnet: { address: "0xFAD6e5e3a9421B9de71A517122D3Bb39A57D6FF5", startBlock: 2902645 } }),
        ...(has(300) && { zksync_sepolia: { address: "0x4E346436e99fb7d6567A2bd024d8806Fc10d84D2", startBlock: 255658 } }),
        ...(has(324) && { zksync_era: { address: "0xA8AC760332770FcF2056040B1f964750e4bEf808", startBlock: 9691 } }),
        ...(has(690) && { redstone: { address: "0xc716c23D75f523eF0C511456528F2A1980256a87", startBlock: 3034954 } }),
        ...(has(777) && { cheapeth: { address: "0xF935d11116fA0103Bd340B663879d325673106f0", startBlock: 13539397 } }),
        ...(has(1101) && { polygon_zkevm: { address: "0x569Dcc6d797265Da700926fe8D10c0DA01717386", startBlock: 1281264 } }),
        ...(has(1301) && { unichain_sepolia: { address: "0x8bF08aE62cbC9a48aaeB473a82DAE2e6D2628517", startBlock: 10747559 } }),
        ...(has(10200) && { chiado: { address: "0x1E732a1C5e9181622DD5A931Ec6801889ce66185", startBlock: 10438389 } }),
        ...(has(17000) && { holesky: { address: "0xd3575b215EC1c3875ad7890982f95EA729DF9537", startBlock: 62519 } }),
        ...(has(42220) && { celo: { address: "0x4C2863bb9969dD693Ec487bED72BDfD83C0cA5b3", startBlock: 31954377 } }),
        ...(has(43114) && { avalanche: { address: "0xD88cd78631Ea0D068cedB0d1357a6eabe59D7502", startBlock: 4090592 } }),
        ...(has(80001) && { mumbai: { address: "0x92115220C28e78312cCe86f3d1dE652CFBD0357A", startBlock: 27425354 } }),
        ...(has(84532) && { base_sepolia: { address: "0x86b653Dc9aa6d7311109276925927087573f91CB", startBlock: 34619265 } }),
        ...(has(421611) && { arbitrum_rinkeby: { address: "0xd3312B4e9225626F8e9a483e2A87bB3966a89f3a", startBlock: 4012956 } }),
        ...(has(421613) && { arbitrum_goerli: { address: "0x14a6748192aBC6E10CA694Ae07bDd4327D6c7A51", startBlock: 19181142 } }),
        ...(has(421614) && { arbitrum_sepolia: { address: "0xB78396EFaF0a177d125e9d45B2C6398Ac5f803B9", startBlock: 41977012 } }),
        ...(has(534353) && { scroll_alpha: { address: [
          "0x4300d4C410f87c7c1824Cbc2eF67431030106604",
          "0xF2D17C08B6A3A60b5A32b95bC9621D292831446b",
        ], startBlock: 2364219 } }),
        ...(has(1337702) && { kintsugi: { address: "0x45fF90518c92C0AcF5C58784435852B5F0CBD4Be", startBlock: 47012 } }),
        ...(has(11155420) && { optimism_sepolia: { address: "0xeAD0ca922390a5E383A9D5Ba4366F7cfdc6f0dbA", startBlock: 14341474 } }),
        ...(has(88558801) && { backstoptestnet1: { address: "0xd05Af7EAB843aA2A04f623c18d2a1C8bB4F301a9", startBlock: 24 } }),
      },
    }}),

    ...((has(100) || has(42161) || has(56) || has(137) || has(4) || has(8) || has(77) || has(10200) || has(421611)) && { RealityETH_v2_1: {
      abi,
      chain: {
        ...(has(100) && { gnosis: { address: "0x79e32aE03fb27B07C89c0c568F80287C01ca2E57", startBlock: 14005802 } }),
        ...(has(42161) && { arbitrum_one: { address: "0x0EDB4CB0B12523749c56Ff24C4a09c0c1417f691", startBlock: 112029 } }),
        ...(has(56) && { bsc: { address: "0xa75ae6d61dd9d55e8153a393e2fc859c6a0fc716", startBlock: 7962044 } }),
        ...(has(137) && { matic: { address: "0xA75AE6D61Dd9d55e8153A393E2fc859c6a0FC716", startBlock: 15610082 } }),
        ...(has(4) && { rinkeby: { address: "0xa09CE5E7943f281A782A0dC021c4029F9088BEC4", startBlock: 8886224 } }),
        ...(has(8) && { ubiq: { address: "0x0dE8A0B6d37FBfD704090245F517e52D7Ad9a903", startBlock: 1621781 } }),
        ...(has(77) && { poa_sokol: { address: "0x90a617ed516ab7fAaBA56CcEDA0C5D952f294d03", startBlock: 18849434 } }),
        ...(has(10200) && { chiado: { address: "0xC68755Ba891A31b969764eB46C0bC7A5127A0854", startBlock: 12569806 } }),
        ...(has(421611) && { arbitrum_rinkeby: { address: "0x592D5cdF8464E3a71C7d5e4C8A549a386B625534", startBlock: 838745 } }),
      },
    }}),

    ...((has(1) || has(4)) && { RealityETH_v2_0: {
      abi,
      chain: {
        ...(has(1) && { mainnet: { address: "0x325a2e0F3CCA2ddbaeBB4DfC38Df8D19ca165b47", startBlock: 6531265 } }),
        ...(has(4) && { rinkeby: { address: "0x3D00D77ee771405628a4bA4913175EcC095538da", startBlock: 3175028 } }),
      },
    }}),

    ...(has(88558801) && { RealityETH_v4_0: {
      abi,
      chain: {
        ...(has(88558801) && { backstoptestnet1: { address: "0x74549fdf4e00C7c564bB193a911887d8C291b13C", startBlock: 2 } }),
      },
    }}),

    ...(has(1) && { RealityETH_ERC20_mainnet: {
      abi,
      chain: {
        mainnet: { address: [
          "0x3D3B51b1091d1F6491AeB1916C94BAfe57f6Cc9d",
          "0x8f1CC53bf34932591177CDA24723486205CA7510",
          "0xf4585A9944A390615E7cec6756C1c082173B93eB",
          "0x33aa365a53a4c9ba777fb5f450901a8eef73f0a9",
          "0x867092A32bC16816F12Fb326EfF7A2865E1ec138",
        ], startBlock: 8050824 },
      },
    }}),

    ...(has(100) && { RealityETH_ERC20_gnosis: {
      abi,
      chain: {
        gnosis: { address: [
          "0x95b2b2b4b66A5a47Df79bF07BEBe72E9870fceb2",
          "0xC9FbdF0df8dE06Ad8d2193F7FA28bdA78c13a102",
          "0x934326a86A99DaB25bB8329089ce73ed9c7c0E4a",
        ], startBlock: 20882108 },
      },
    }}),

    ...(has(56) && { RealityETH_ERC20_bsc: {
      abi,
      chain: {
        bsc: { address: "0x95f8fc16C7Bd5a5b24CaE629471c6cCC3916826A", startBlock: 13749748 },
      },
    }}),

    ...(has(137) && { RealityETH_ERC20_matic: {
      abi,
      chain: {
        matic: { address: [
          "0x83d3f4769a19f1b43337888b0290f5473cf508b2",
          "0x3155836D28C0845c37791808287FaFC811742C5a",
        ], startBlock: 42899867 },
      },
    }}),

    ...(has(11155111) && { RealityETH_ERC20_sepolia: {
      abi,
      chain: {
        sepolia: { address: "0x8A5f1C6361E280348a59daC10160A88428FFBd51", startBlock: 8526475 },
      },
    }}),

    ...(has(4) && { RealityETH_ERC20_rinkeby: {
      abi,
      chain: {
        rinkeby: { address: [
          "0xa4dA771Bbd6e93bB8e714Fe97b388fe88eec8288",
          "0x3B3ab861Deb4ED756e39f2f6A2634DEdfC182d38",
          "0x5e97Dd72812B59cB3166B0D907a9B360493b9971",
        ], startBlock: 4643634 },
      },
    }}),

    ...(has(80001) && { RealityETH_ERC20_mumbai: {
      abi,
      chain: {
        mumbai: { address: "0x895b09919250f81505c089651d3cb61d284531d3", startBlock: 35623862 },
      },
    }}),

  },
});
